In [43]:
print("Hello World")

Hello World


## 00. PyTorch Fundamentals

Resource Book: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [44]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [45]:
!nvidea-smi ##I am guessing the free version does not any Nvidea drivers ggs I guess

/bin/bash: line 1: nvidea-smi: command not found


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.tensors()` = https://pytorch.org/docs/stable/tensors.html

In [46]:
#scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [47]:
scalar.ndim

0

In [48]:
scalar.shape

torch.Size([])

In [49]:
#Get tensor back as Python int
x = scalar.item()
print(x)
type(x)

7


int

In [50]:
#vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [51]:
vector.ndim

1

In [52]:
vector.shape

torch.Size([2])

In [53]:
#Matrix

MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [54]:
MATRIX[0]

tensor([1, 2])

In [55]:
MATRIX[1]

tensor([3, 4])

In [56]:
MATRIX[0][1].item()

2

In [57]:
MATRIX.ndim

2

In [58]:
MATRIX.shape

torch.Size([2, 2])

In [59]:
#TENSOR
TENSOR = torch.tensor([[[[1,3,2],[4,5,6],[8,9,10]],[[1,3,2],[4,5,6],[8,9,10]]]])

In [60]:
TENSOR.ndim

4

In [61]:
TENSOR.shape

torch.Size([1, 2, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks work is that they start with random tensors and then they later adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update the random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [62]:
### Creating a random tensor of size (4,3)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.9001, 0.6155, 0.1170, 0.2208],
        [0.7284, 0.6690, 0.3359, 0.5556],
        [0.5893, 0.0555, 0.2159, 0.7303]])

In [63]:
random_tensor.ndim

2

In [64]:
random_tensor.shape

torch.Size([3, 4])

In [65]:
# Create a random tensor with a simmilar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels

random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [66]:
random_image_size_tensor

tensor([[[0.8161, 0.6214, 0.3590],
         [0.8291, 0.3721, 0.1190],
         [0.5856, 0.6116, 0.2043],
         ...,
         [0.8192, 0.5660, 0.5267],
         [0.9164, 0.5373, 0.9758],
         [0.9844, 0.3333, 0.4742]],

        [[0.5767, 0.2101, 0.8622],
         [0.1140, 0.3204, 0.5651],
         [0.0206, 0.7195, 0.2388],
         ...,
         [0.2316, 0.4054, 0.9968],
         [0.8215, 0.8979, 0.4953],
         [0.3783, 0.9164, 0.6872]],

        [[0.4302, 0.7373, 0.8564],
         [0.4375, 0.7543, 0.6508],
         [0.9935, 0.6473, 0.9186],
         ...,
         [0.1740, 0.6557, 0.8476],
         [0.9340, 0.0135, 0.9959],
         [0.7563, 0.6486, 0.8099]],

        ...,

        [[0.8053, 0.6854, 0.3630],
         [0.3746, 0.5519, 0.7645],
         [0.7574, 0.1276, 0.2284],
         ...,
         [0.1965, 0.3932, 0.4601],
         [0.6065, 0.1984, 0.9629],
         [0.0632, 0.3411, 0.5945]],

        [[0.7300, 0.1734, 0.3238],
         [0.3276, 0.5714, 0.3964],
         [0.

###Zeroes and Ones

In [67]:
# Create a tensor with all zeroes
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [68]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [70]:
random_tensor*ones

tensor([[0.9001, 0.6155, 0.1170, 0.2208],
        [0.7284, 0.6690, 0.3359, 0.5556],
        [0.5893, 0.0555, 0.2159, 0.7303]])

In [71]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [72]:
one_to_ten = torch.arange(start = 1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

**Note:** Tensor datatypes in one of the 3 big errors that I will run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [75]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.3,6.0,9.], dtype= None, device=None, requires_grad=False)
float_32_tensor

tensor([3.3000, 6.0000, 9.0000])

In [76]:
float_32_tensor.dtype

torch.float32

In [77]:
float_16_tensor = float_32_tensor.type(torch.float16) # an also use float_32_tensor.type(torch.half)
float_16_tensor.dtype

torch.float16

In [78]:
temp = float_16_tensor + float_32_tensor
temp , temp.dtype

(tensor([ 6.6008, 12.0000, 18.0000]), torch.float32)

In [79]:
 int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
 int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [80]:
int_32_tensor * float_32_tensor

tensor([ 9.9000, 36.0000, 81.0000])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatypr of the tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape of the tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device of the tensor, can use `tensor.device`

In [81]:
int_32_tensor.device

device(type='cpu')

In [82]:
# Create a tensor

some_tensor = torch.rand(size=(3,4), dtype=torch.float16)
some_tensor

tensor([[0.5444, 0.8306, 0.0962, 0.7378],
        [0.1650, 0.4883, 0.6426, 0.1587],
        [0.8867, 0.2427, 0.5215, 0.9604]], dtype=torch.float16)

In [83]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.5444, 0.8306, 0.0962, 0.7378],
        [0.1650, 0.4883, 0.6426, 0.1587],
        [0.8867, 0.2427, 0.5215, 0.9604]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


In [84]:
device = torch.device("cuda:0")

tensor_on_gpu = some_tensor.to(device)

tensor_on_gpu.device

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### Manipulating Tensors (tensor operations)
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [85]:
# Create a tensor

tensor = torch.tensor([1,2,3])

In [86]:
#Add tensor by 10
tensor + 10

tensor([11, 12, 13])

In [87]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
#Subtract tensor by 10
tensor - 10

In [ ]:
# Try out Pytorch in-built function
torch.mul(tensor,10)

In [89]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are 2 main rules that matrix multiplication has to satisfy
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(3,2) @ (2,3)` will work and return `(3,3)` dimension tensor
* `(2,3) @ (3,2)` will work and return `(2,2)` dimension tensor
* `(2,3) @ (2,3)` wont work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(3,2) @ (2,3) -> (3,3)`
* `(2,3)` @ (3,2) -> (2,2)`

In [91]:
#wont work cause (3,2)@(3,2)
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [92]:
#should return a (3,3) dim tensor
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.0982, 0.4360, 0.3578],
        [0.0678, 0.6120, 0.4500],
        [0.0141, 0.4391, 0.2971]])

In [93]:
# Element wise multiplication

print(tensor, '*', tensor)
print(f'Equals:{tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [94]:
# Matrix multiplication
tensor.ndim,tensor.shape

torch.matmul(tensor,tensor)

tensor(14)

In [95]:
# Matrix multiplication (but its not really but it also is - cause its 1d matrix its transposing the second tensor and then multiplying)

1*1 + 2*2 + 3*3

14

In [96]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.81 ms, sys: 0 ns, total: 1.81 ms
Wall time: 1.9 ms


In [97]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 93 µs, sys: 0 ns, total: 93 µs
Wall time: 98.5 µs


tensor(14)

In [98]:
# @ can also be used for matrix multiplication but it is not recommended
%%time
tensor @ tensor

CPU times: user 91 µs, sys: 14 µs, total: 105 µs
Wall time: 109 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [99]:
#Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

In [100]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [101]:
# torch.mm(tensor_A,tensor_B) is an alias for torch.matmul(torch_A,torch_B)

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate one our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given matrix


In [102]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [103]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [104]:
#The matrix multiplication operation works when tensor_B is transposed

print('The Original Shapes: tensor_A = {0}, tensor_B = {1}'.format(tensor_A.shape, tensor_B.shape))
print('The New Shapes: tensor_A = {0} (same as above), tensor_B = {1}'.format(tensor_A.shape,tensor_B.T.shape))
print('Multiplying: {} @ {} <- inner dimmension must match!'.format(tensor_A.shape,tensor_B.T.shape))
print('\nOutput:')
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print('Output Shape: {}'.format(output.shape))

The Original Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
The New Shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimmension must match!

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output Shape: torch.Size([3, 3])


In [108]:
# Messing around - this should (2,3) @ (3,2) -> (2,2)

torch.mm(tensor_A.T, tensor_B), torch.mm(tensor_A.T, tensor_B).shape


(tensor([[ 76, 103],
         [100, 136]]),
 torch.Size([2, 2]))


### Finding the min, max, mean, sum, etc (tensor aggregation)
